



Epoch 0:  50%|█████████████████████████████████████████████████████████████████████████                                                                         | 1/2 [01:52<01:52, 112.77s/it, loss=0.772, v_num=zfoo]
Validation: 0it [00:00, ?it/s]
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x2ba6ade21c10>
Traceback (most recent call last):
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1291, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
