Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/6
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/6
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/6
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/6
Initializing distributed: GLOBAL_RANK: 4, MEMBER: 5/6
Initializing distributed: GLOBAL_RANK: 5, MEMBER: 6/6
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 6 processes
----------------------------------------------------------------------------------------------------
LOCAL_RANK: 4 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
LOCAL_RANK: 5 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
  | Name      | Type              | Params
------------------------------------------------
0 | accuracy  | Accuracy          | 0
1 | calc_loss | BCEWithLogitsLoss | 0
2 | l1        | Linear            | 9.0 K
3 | sm        | Sigmoid           | 0
------------------------------------------------
9.0 K     Trainable params
0         Non-trainable params
9.0 K     Total params
0.018     Total estimated model params size (MB)
[34m[1mwandb[39m[22m: Currently logged in as: [33mzedrover[39m ([33msfcap[39m). Use [1m`wandb login --relogin`[22m to force relogin
Sanity Checking: 0it [00:00, ?it/s]
[34m[1mwandb[39m[22m: Tracking run with wandb version 0.12.16
[34m[1mwandb[39m[22m: Run data is saved locally in [35m[1m/lustre/home/acct-aemwx/aemwx-user1/wangyu/my/nlp-final/notebook/pl/wandb/run-20220526_114951-33vw2gk5
[34m[1mwandb[39m[22m: Run [1m`wandb offline`[22m to turn off syncing.
[34m[1mwandb[39m[22m: Syncing run [33mconfused-eon-11
[34m[1mwandb[39m[22m: ‚≠êÔ∏è View project at [34m[4mhttps://wandb.ai/sfcap/baseline

Epoch 0:   0%|                                                                                                                                                                                   | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x2af729517c10>
Traceback (most recent call last):
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 263, in run_path
    prepare(preparation_data)
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 96, in _run_module_code
    return _run_module_code(code, init_globals, run_name,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 96, in _run_module_code
    exitcode = _main(fd, parent_sentinel)
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    self._shutdown_workers()
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1291, in _shutdown_workers
    _run_code(code, mod_globals, init_globals,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 86, in _run_code
    _run_code(code, mod_globals, init_globals,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 86, in _run_code
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x2ac594e5fc10>
Traceback (most recent call last):
    prepare(preparation_data)
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    exec(code, run_globals)
  File "/lustre/home/acct-aemwx/aemwx-user1/wangyu/my/nlp-final/notebook/pl/baseline.py", line 8, in <module>
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x2b26526e5c10>
Traceback (most recent call last):
    exec(code, run_globals)
  File "/lustre/home/acct-aemwx/aemwx-user1/wangyu/my/nlp-final/notebook/pl/baseline.py", line 8, in <module>
    _fixup_main_from_path(data['init_main_from_path'])cc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    import matplotlib.pyplot as plt
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 50, in <module>
    prepare(preparation_data)
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    exitcode = _main(fd, parent_sentinel)
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    import matplotlib.pyplot as plt
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 52, in <module>
    prepare(preparation_data)
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 263, in run_path
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
    _fixup_main_from_path(data['init_main_from_path'])
    prepare(preparation_data)
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    self._shutdown_workers()
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1291, in _shutdown_workers
    main_content = runpy.run_path(main_path,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 263, in run_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 263, in run_path
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x2b0b2dd0dc10>
Traceback (most recent call last):
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    return _run_module_code(code, init_globals, run_name,
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x2af4a5860c10>
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 96, in _run_module_code
Traceback (most recent call last):
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1291, in _shutdown_workers
    main_content = runpy.run_path(main_path,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 263, in run_path
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x2abbdea92c10>
Traceback (most recent call last):
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    return _run_module_code(code, init_globals, run_name,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 96, in _run_module_code
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
    self._shutdown_workers()
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1291, in _shutdown_workers
    return _run_module_code(code, init_globals, run_name,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 96, in _run_module_code
    self._shutdown_workers()
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1291, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
    _run_code(code, mod_globals, init_globals,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 86, in _run_code
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
    from matplotlib import rcsetup, style
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/style/__init__.py", line 1, in <module>
    _run_code(code, mod_globals, init_globals,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 86, in _run_code
    import matplotlib.image
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/image.py", line 216, in <module>
    exec(code, run_globals)
  File "/lustre/home/acct-aemwx/aemwx-user1/wangyu/my/nlp-final/notebook/pl/baseline.py", line 7, in <module>
    return _run_module_code(code, init_globals, run_name,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 96, in _run_module_code
    self._shutdown_workers()
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1291, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
    class _ImageBase(martist.Artist, cm.ScalarMappable):
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 119, in __init_subclass__
    import torch
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/__init__.py", line 519, in <module>
    from .serialization import save, load
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/serialization.py", line 8, in <module>
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
    _run_code(code, mod_globals, init_globals,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 86, in _run_code
    _run_code(code, mod_globals, init_globals,
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/runpy.py", line 86, in _run_code
    from .core import use, context, available, library, reload_library
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1342, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1314, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1443, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1483, in _fill_cache
KeyboardInterrupt
    cls._update_set_signature_and_docstring()
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 140, in _update_set_signature_and_docstring
    import tarfile
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 874, in get_code
  File "<frozen importlib._bootstrap_external>", line 973, in get_data
KeyboardInterrupt
    exec(code, run_globals)
  File "/lustre/home/acct-aemwx/aemwx-user1/wangyu/my/nlp-final/notebook/pl/baseline.py", line 7, in <module>
    exec(code, run_globals)
  File "/lustre/home/acct-aemwx/aemwx-user1/wangyu/my/nlp-final/notebook/pl/baseline.py", line 8, in <module>
    exec(code, run_globals)
  File "/lustre/home/acct-aemwx/aemwx-user1/wangyu/my/nlp-final/notebook/pl/baseline.py", line 7, in <module>
    for prop in ArtistInspector(cls).get_setters()
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 1345, in __init__
    import torch
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/__init__.py", line 635, in <module>
    import torch
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/__init__.py", line 630, in <module>
    import torch.utils.data
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/__init__.py", line 6, in <module>
    import torch.backends.mkl
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 874, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
KeyboardInterrupt
    import matplotlib.pyplot as plt
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 57, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 25, in <module>
    self.aliasd = self.get_aliases()
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 1364, in get_aliases
    if not self.is_alias(func):
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 1443, in is_alias
    ds = inspect.getdoc(o)
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/inspect.py", line 613, in getdoc
    from .dataloader import DataLoader, _DatasetKind, get_worker_info
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 21, in <module>
    from . import _utils
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/_utils/__init__.py", line 45, in <module>
    from matplotlib import _blocking_input, docstring, projections
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/projections/__init__.py", line 56, in <module>
    from . import worker, signal_handling, pin_memory, collate, fetch
  File "/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 14, in <module>
    from . import signal_handling, MP_STATUS_CHECK_INTERVAL, IS_WINDOWS
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 874, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
    doc = object.__doc__
KeyboardInterrupt
KeyboardInterrupt
    from .geo import AitoffAxes, HammerAxes, LambertAxes, MollweideAxes
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/projections/geo.py", line 299, in <module>
    class HammerAxes(GeoAxes):
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 119, in __init_subclass__
    cls._update_set_signature_and_docstring()
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 147, in _update_set_signature_and_docstring
    + kwdoc(cls))
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 1749, in kwdoc
    'Properties:\n' + '\n'.join(ai.pprint_setters(leadingspace=4)))
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 1509, in pprint_setters
    for prop in sorted(self.get_setters()):
  File "/lustre/home/acct-aemwx/aemwx-user1/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 1430, in get_setters
    for name in dir(self.o):
KeyboardInterrupt
[34m[1mwandb[39m[22m: Waiting for W&B process to finish... [32m(success).
[34m[1mwandb[39m[22m: \ 0.001 MB of 0.001 MB uploaded (0.000 MB deduped)
[34m[1mwandb[39m[22m: \ 0.001 MB of 0.001 MB uploaded (0.000 MB deduped)
[34m[1mwandb[39m[22m: \ 0.001 MB of 0.001 MB uploaded (0.000 MB deduped)
[34m[1mwandb[39m[22m: \ 0.001 MB of 0.001 MB uploaded (0.000 MB deduped)
[34m[1mwandb[39m[22m: \ 0.001 MB of 0.001 MB uploaded (0.000 MB deduped)
[34m[1mwandb[39m[22m: \ 0.001 MB of 0.001 MB uploaded (0.000 MB deduped)
[34m[1mwandb[39m[22m: \ 0.001 MB of 0.001 MB uploaded (0.000 MB deduped)
[34m[1mwandb[39m[22m: \ 0.001 MB of 0.001 MB uploaded (0.000 MB deduped)
[34m[1mwandb[39m[22m: \ 0.001 MB of 0.001 MB uploaded (0.000 MB deduped)
[34m[1mwandb[39m[22m: \ 0.001 MB of 0.001 MB uploaded (0.000 MB deduped)
[34m[1mwandb[39m[22m: \ 0.001 MB of 0.001 MB uploaded (0.000 MB deduped)